### Importing Necessary Dependencies

In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split as tts
from sklearn.datasets import load_breast_cancer

### Loading The Dataset

In [45]:
_data = load_breast_cancer()

In [36]:
print(f"Features : {_data.data}")

Features : [[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [37]:
print(f"Target : {_data.target}")

Target : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1

In [38]:
print(f"Feature names : {_data.feature_names}")

Feature names : ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [39]:
df = pd.DataFrame(_data.data, columns = _data.feature_names)
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [40]:
df["target"] = _data.target

In [41]:
df.sample(10)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
285        12.58         18.40           79.83      489.0          0.08393   
107        12.36         18.54           79.01      466.7          0.08477   
104        10.49         19.29           67.41      336.1          0.09989   
119        17.95         20.01          114.20      982.0          0.08402   
72         17.20         24.52          114.20      929.4          0.10710   
124        13.37         16.39           86.10      553.5          0.07115   
362        12.76         18.84           81.87      496.6          0.09676   
32         17.02         23.98          112.80      899.3          0.11970   
315        12.49         16.85           79.19      481.6          0.08511   
255        13.96         17.05           91.43      602.4          0.10960   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
285           0.04216        0.001860             0.002924         0.1697   
107           0.06815        0.026430             0.019210         0.1602   
104           0.08578        0.029950             0.012010         0.2217   
119           0.06722        0.072930             0.055960         0.2129   
72            0.18300        0.169200             0.079440         0.1927   
124           0.07325        0.080920             0.028000         0.1422   
362           0.07952        0.026880             0.017810         0.1759   
32            0.14960        0.241700             0.120300         0.2248   
315           0.03834        0.004473             0.006423         0.1215   
255           0.12790        0.097890             0.052460         0.1908   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
285                 0.05855  ...          23.08            85.56       564.1   
107                 0.06066  ...          27.49            85.56       544.1   
104                 0.06481  ...          23.31            74.22       402.8   
119                 0.05025  ...          27.83           129.20      1261.0   
72                  0.06487  ...          33.82           151.60      1681.0   
124                 0.05823  ...          22.75            91.99       632.1   
362                 0.06183  ...          25.99            87.82       579.7   
32                  0.06382  ...          32.09           136.10      1344.0   
315                 0.05673  ...          19.71            84.48       544.2   
255                 0.06130  ...          22.07           108.10       826.0   

     worst smoothness  worst compactness  worst concavity  \
285            0.1038            0.06624         0.005579   
107            0.1184            0.19630         0.193700   
104            0.1219            0.14860         0.079870   
119            0.1072            0.12020         0.224900   
72             0.1585            0.73940         0.656600   
124            0.1025            0.25310         0.330800   
362            0.1298            0.18390         0.125500   
32             0.1634            0.35590         0.558800   
315            0.1104            0.04953         0.019380   
255            0.1512            0.32620         0.320900   

     worst concave points  worst symmetry  worst fractal dimension  target  
285              0.008772          0.2505                  0.06431       1  
107              0.084420          0.2983                  0.07185       1  
104              0.032030          0.2826                  0.07552       1  
119              0.118500          0.4882                  0.06111       0  
72               0.189900          0.3313                  0.13390       0  
124              0.089780          0.2048                  0.07628       1  
362              0.083120          0.2744                  0.07238       1  
32               0.184700          0.3530                  0.08482       0  
315              0.027840          0.1917           

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [48]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [42]:
df.shape

(569, 31)

In [46]:
df["target"].value_counts()

1    357
0    212
Name: target, dtype: int64

#### 1 ---> Benign
#### 0 ---> Malignant

In [50]:
df.groupby("target").mean()

mean radius  mean texture  mean perimeter   mean area  \
target                                                          
0         17.462830     21.604906      115.365377  978.376415   
1         12.146524     17.914762       78.075406  462.790196   

        mean smoothness  mean compactness  mean concavity  \
target                                                      
0              0.102898          0.145188        0.160775   
1              0.092478          0.080085        0.046058   

        mean concave points  mean symmetry  mean fractal dimension  ...  \
target                                                              ...   
0                  0.087990       0.192909                0.062680  ...   
1                  0.025717       0.174186                0.062867  ...   

        worst radius  worst texture  worst perimeter   worst area  \
target                                                              
0          21.134811      29.318208       141.370330  1422.286321   
1          13.379801      23.515070        87.005938   558.899440   

        worst smoothness  worst compactness  worst concavity  \
target                                                         
0               0.144845           0.374824         0.450606   
1               0.124959           0.182673         0.166238   

        worst concave points  worst symmetry  worst fractal dimension  
target                                                                 
0                   0.182237        0.323468                 0.091530  
1                   0.074444        0.270246                 0.079442  

[2 rows x 30 columns]